# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4abca53336483851108d929202800f687490a9fd58c675ce49e283b69bd0d492e2b51f5ce676a6862896d9b9002a35e2b087e06065b81dcd6b48aa56aa9ccb2

test:
  secret_key_base: 79ca2037618cba1e992592a1b02698f1b987031a4e11fac399dbcecf7e24eafc99b5bd10b21f306390f8a68c7465c4e27ff64c5de627fd5a0bf55f9314a54862

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
